### ISSUE TITLE
phpagi warning: mkdir(): File exists

### ISSUE THREAD

**Issue by JoseGoncalves** [radiusone/a2billing#11]
As the [phpagi GitHub Repo](https://github.com/radiusone/phpagi) does not have Issues enabled, I'm posting here an issue with it.

Whenever a call is made that goes through A2Billing, I'm getting the following warning:

> /var/www/html/a2billing/vendor/radiusone/phpagi/src/AGI.php[153]: mkdir(): File exists

which comes from this code:

```php
if (!mkdir($tempdir, 0775, true)) {
    $this->conlog('Unable to create temp dir $tempdir, carrying on');
}
```

It would be better to wrap that code with a directory check to avoid filling the logs with such warnings, i.e.,
```php
if (!is_dir($tempdir)) {
    if (!mkdir($tempdir, 0775, true)) {
        $this->conlog('Unable to create temp dir $tempdir, carrying on');
    }
}
```

**Comment by miken32** [comment]
Personally would do both in one `if` statement but looks good to me. If you file a PR I’ll merge it. I’m out of town for a few weeks and don’t have access to my laptop to do any work myself.

**Comment by JoseGoncalves** [comment]
OK. I'll do that.
