### ISSUE TITLE
Unable to add administrators

### ISSUE THREAD

**Issue by JoseGoncalves** [radiusone/a2billing#5]
Using the Web UI I'm unable to add administrators in section `Admin` -> `Add :: Search`.

The `Add` form appears when I press the `Add ADMINISTRATOR` button but, after I fill up that form and press the `Confirm Data` button, a message `Your new Administrator hasn't been inserted` apears and I see no errors on the Apache log file.

**Comment by miken32** [comment]
Fixed in c6adcfaa
